package com.wecreate.api.shared.dtos.dashboard;

import lombok.AllArgsConstructor;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;
import java.util.UUID;

@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
public class CheckoutRequest {
    // The specific website project workspace the client is paying for
    private UUID projectId;

    // The chosen strategy tier: "ONE_MONTH", "THREE_MONTHS", or "SUBSCRIPTION"
    private String planType;

    // Idempotency token generated by Angular to prevent double-charging on glitchy clicks
    private String clientToken;
}